#!/usr/bin/env bash
#
# Regenerate terraform.md after a Renovate upgrade.
#
# terraform-docs (markdown table, mode: inject -- see .terraform-docs.yml) renders
# a Modules table whose Source column embeds the git `?ref=<sha>` pin. A digest
# bump to terraform-modules therefore leaves the committed terraform.md stale
# with no variable, output or resource change to hint at it -- PR #26 bumped
# `4cbebdd` -> `2b3a372` in four module blocks and shipped a terraform.md still
# advertising the old sha. Renovate cannot infer that; only re-running the
# generator fixes it. This runs via postUpgradeTasks (see renovate.json) so the
# refreshed doc lands in Renovate's OWN commit, which also keeps the branch
# single-author and therefore still rebaseable by Renovate.
#
# Before this repo had PR CI the drift was merely invisible (it shipped that way
# in #18). Now ci.yml runs .pre-commit-config.yaml verbatim and its terraform-docs
# hook WRITES, so every Renovate PR that touches a module ref or a provider
# constraint is red until the doc is regenerated by hand.
#
# Runs INSIDE the Renovate container, which has no Docker socket mounted (the
# reusable workflow leaves the action's `mount-docker-socket` at its default of
# false), so this fetches the static binary rather than reusing the `docker run
# quay.io/terraform-docs/terraform-docs` invocation that pre-commit uses. Same
# generator, different delivery.
set -euo pipefail

# MUST equal the tag on .pre-commit-config.yaml's terraform-docs hook: CI runs
# that hook and fails on any file it rewrites, so docs generated here at a
# different version are rejected there (output changes between minor versions --
# 0.19.0 vs 0.20.0 moved the separator style). The assertion below enforces it,
# and renovate.json's customManager bumps both pins in one PR.
VERSION="0.24.0"

PRECOMMIT_PIN="$(grep -oE 'quay\.io/terraform-docs/terraform-docs:[0-9]+\.[0-9]+\.[0-9]+' \
  .pre-commit-config.yaml | head -n1 | cut -d: -f2 || true)"
if [ -z "${PRECOMMIT_PIN}" ]; then
  echo "no terraform-docs pin found in .pre-commit-config.yaml" >&2
  exit 1
fi
if [ "${PRECOMMIT_PIN}" != "${VERSION}" ]; then
  echo "terraform-docs pin skew: this script uses ${VERSION}, .pre-commit-config.yaml uses ${PRECOMMIT_PIN}" >&2
  echo "  CI runs pre-commit, so docs generated here would be rewritten and fail it." >&2
  exit 1
fi

TMP="$(mktemp -d)"
trap 'rm -rf "${TMP}"' EXIT

# The Renovate executor may run on either amd64 or arm64 (the OCI fleet is
# Ampere A1/arm64), so pick the matching release asset. A hardcoded amd64 binary
# dies there with a bare "Exec format error" that reads like a corrupt download.
case "$(uname -m)" in
  x86_64) ARCH="amd64" ;;
  aarch64 | arm64) ARCH="arm64" ;;
  *) echo "unsupported arch: $(uname -m)" >&2; exit 1 ;;
esac

TARBALL="terraform-docs-v${VERSION}-linux-${ARCH}.tar.gz"
curl -sSfL --retry 3 --retry-delay 2 \
  "https://terraform-docs.io/dl/v${VERSION}/${TARBALL}" -o "${TMP}/${TARBALL}"

# Verify before executing. This runs inside Renovate's container, on a branch,
# unattended, with a token in the environment -- the least observed place in the
# fleet to be running an unverified binary. Checksums come from the release
# rather than being stored beside VERSION: a stored constant is one more pin
# that can fall behind the version above.
SUMS="$(curl -sSfL --retry 3 --retry-delay 2 \
  "https://github.com/terraform-docs/terraform-docs/releases/download/v${VERSION}/terraform-docs-v${VERSION}.sha256sum")"
EXPECTED="$(awk -v t="${TARBALL}" '$2 == t {print $1}' <<<"${SUMS}")"
if [ -z "${EXPECTED}" ]; then
  echo "release v${VERSION} publishes no checksum for ${TARBALL}" >&2
  exit 1
fi
ACTUAL="$(sha256sum "${TMP}/${TARBALL}" | awk '{print $1}')"
if [ "${EXPECTED}" != "${ACTUAL}" ]; then
  echo "checksum mismatch for ${TARBALL}" >&2
  echo "  expected ${EXPECTED}" >&2
  echo "  actual   ${ACTUAL}" >&2
  exit 1
fi

tar -xz -C "${TMP}" -f "${TMP}/${TARBALL}" terraform-docs

# One root module, so one invocation -- the same argument .pre-commit-config.yaml
# passes its hook. .terraform-docs.yml carries the output file, inject mode and
# `lockfile: false`, so the committed .terraform.lock.hcl cannot make this render
# resolved provider versions where CI renders constraints.
"${TMP}/terraform-docs" .
